In [1]:
# numpy
import numpy as np

In [11]:
arr = np.arange(15).reshape(3,5)
print(arr, type(arr))
print(arr.ndim) # 차원
print(arr.shape, arr.size, arr.dtype.name) # shape : 3 * 5
print(arr.dtype.itemsize) # 데이터 저장 공간 사이즈 : 4byte

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] <class 'numpy.ndarray'>
2
(3, 5) 15 int32
4


In [5]:
a_list = list(range(15))
a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [20]:
arr = np.arange(-5,5,0.5)
arr = arr.reshape(4, int(arr.size/4))
print(arr, '\n')

arr1 = arr.flatten()
print(arr1)   # 다차원을 1차원으로 변형
arr1.ndim

[[-5.  -4.5 -4.  -3.5 -3. ]
 [-2.5 -2.  -1.5 -1.  -0.5]
 [ 0.   0.5  1.   1.5  2. ]
 [ 2.5  3.   3.5  4.   4.5]] 

[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5
  2.   2.5  3.   3.5  4.   4.5]


1

In [23]:
# 기존의 파이썬 리스트로 array 생성
list_a = np.array([1,2,3])
list_b = np.array([[1,2,3] , [4,5,6]])

print("list_a : {}, list_a의 type : {}".format(list_a, type(list_a)))
print("list_b : {}, list_b의 type : {}".format(list_b, type(list_b)))
print()
print("list_a dim: {}, list_a의 shape : {}".format(list_a.ndim, list_a.shape))
print("list_b dim: {}, list_b의 shape : {}".format(list_b.ndim, list_b.shape))
print()
print("list_a 사이즈: {}, list_a의 타입 : {}".format(list_a.size, list_a.dtype))
print("list_b 사이즈: {}, list_b의 타입 : {}".format(list_b.size, list_b.dtype))

list_a : [1 2 3], list_a의 type : <class 'numpy.ndarray'>
list_b : [[1 2 3]
 [4 5 6]], list_b의 type : <class 'numpy.ndarray'>

list_a dim: 1, list_a의 shape : (3,)
list_b dim: 2, list_b의 shape : (2, 3)

list_a 사이즈: 3, list_a의 타입 : int32
list_b 사이즈: 6, list_b의 타입 : int32
